import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import * as schema from './schema.js';

export interface DatabaseOptions {
  readonly?: boolean;
  fileMustExist?: boolean;
  timeout?: number;
  verbose?: (message?: unknown, ...additionalArgs: unknown[]) => void;
  nativeBinding?: string;
}

export interface DatabaseConfig {
  filename?: string;
  options?: DatabaseOptions;
}

export function createDatabase(config?: DatabaseConfig) {
  const filename = config?.filename || './conduit.db';
  const options = config?.options || {};

  const sqlite = new Database(filename, options);

  sqlite.pragma('journal_mode = WAL');
  sqlite.pragma('foreign_keys = ON');
  sqlite.pragma('synchronous = NORMAL');

  const db = drizzle(sqlite, { schema });

  return db;
}

export function initializeSchema(db: Database) {
  // For in-memory databases, use the exact SQL generated by drizzle-kit
  // This is copied from src/migrations/0000_brave_vision.sql to stay in sync with our schema
  const sqlite = (db as any).$client;

  const schemaSQL = `
    CREATE TABLE article_tags (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      article_id integer NOT NULL,
      tag_id integer NOT NULL,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (article_id) REFERENCES articles(id) ON UPDATE no action ON DELETE cascade,
      FOREIGN KEY (tag_id) REFERENCES tags(id) ON UPDATE no action ON DELETE cascade
    );

    CREATE TABLE articles (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      slug text NOT NULL,
      title text NOT NULL,
      description text NOT NULL,
      body text NOT NULL,
      author_id integer NOT NULL,
      favorites_count integer DEFAULT 0 NOT NULL,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (author_id) REFERENCES users(id) ON UPDATE no action ON DELETE cascade
    );

    CREATE UNIQUE INDEX articles_slug_unique ON articles (slug);

    CREATE TABLE comments (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      body text NOT NULL,
      author_id integer NOT NULL,
      article_id integer NOT NULL,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (author_id) REFERENCES users(id) ON UPDATE no action ON DELETE cascade,
      FOREIGN KEY (article_id) REFERENCES articles(id) ON UPDATE no action ON DELETE cascade
    );

    CREATE TABLE favorites (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      user_id integer NOT NULL,
      article_id integer NOT NULL,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE no action ON DELETE cascade,
      FOREIGN KEY (article_id) REFERENCES articles(id) ON UPDATE no action ON DELETE cascade
    );

    CREATE TABLE follows (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      follower_id integer NOT NULL,
      following_id integer NOT NULL,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (follower_id) REFERENCES users(id) ON UPDATE no action ON DELETE cascade,
      FOREIGN KEY (following_id) REFERENCES users(id) ON UPDATE no action ON DELETE cascade
    );

    CREATE TABLE tags (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      name text NOT NULL,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
    );

    CREATE UNIQUE INDEX tags_name_unique ON tags (name);

    CREATE TABLE users (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      email text NOT NULL,
      username text NOT NULL,
      password text NOT NULL,
      bio text,
      image text,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
    );

    CREATE UNIQUE INDEX users_email_unique ON users (email);
    CREATE UNIQUE INDEX users_username_unique ON users (username);
  `;

  sqlite.exec(schemaSQL);
}

export type Database = ReturnType<typeof createDatabase>;

export { schema };